apiVersion: apps/v1
kind: Deployment
metadata:
  name: seservice
  labels:
    app: seservice
spec:
  replicas: 1
  template:
    metadata:
      name: seservice
      labels:
        app: seservice
    spec:
      containers:
        - name: seservice
          image: index.docker.io/irisdev21/seservice:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: seservice

---
apiVersion: v1
kind: Service
metadata:
  name: seservice
spec:
  selector:
    app: seservice
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP